[features]
seeds = false
skip-lint = false

[programs.devnet]
delta_vault = "FQ99NWkE3f6HUdMcG312FCWvAT4iR4DTrTb9JA8xi471"

[programs.mainnet]
delta_vault = "FQ99NWkE3f6HUdMcG312FCWvAT4iR4DTrTb9JA8xi471"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/delta_vault"]
