#!/usr/bin/env node
/**
 * setup-devnet.js
 * Run this once to get your devnet environment ready.
 *
 * What it does:
 *   1. Generates a fresh Solana keypair (or loads existing)
 *   2. Airdrops 2 SOL on devnet
 *   3. Creates a USDC token account
 *   4. Mints devnet USDC from the Drift faucet
 *   5. Writes a ready-to-use .env file
 *   6. Prints a checklist of what's left to do manually
 *
 * Usage:
 *   node scripts/setup-devnet.js
 */

const {
  Connection,
  Keypair,
  PublicKey,
  LAMPORTS_PER_SOL,
  SystemProgram,
  Transaction,
} = require("@solana/web3.js");
const {
  createAssociatedTokenAccountInstruction,
  getAssociatedTokenAddress,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
} = require("@solana/spl-token");
const fs   = require("fs");
const path = require("path");
const https = require("https");

// ── Config ────────────────────────────────────────────────────────────────────
const DEVNET_RPC   = "https://api.devnet.solana.com";
const KEYPAIR_PATH = path.join(__dirname, "../keypair.json");
const ENV_PATH     = path.join(__dirname, "../bot/.env");

// Devnet token mints (Drift devnet)
const DEVNET_USDC_MINT = new PublicKey("8zGuJQqwhZafTah7Uc7Z4tXRnguqkn5KLFAP8oV6PHe2");
const DRIFT_DEVNET_PROGRAM = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH";

// ── Colors ────────────────────────────────────────────────────────────────────
const G = (s) => `\x1b[32m${s}\x1b[0m`;
const Y = (s) => `\x1b[33m${s}\x1b[0m`;
const R = (s) => `\x1b[31m${s}\x1b[0m`;
const B = (s) => `\x1b[36m${s}\x1b[0m`;
const W = (s) => `\x1b[1m${s}\x1b[0m`;

async function main() {
  console.log("\n" + W("═══════════════════════════════════════════════"));
  console.log(W(" Delta Vault — Devnet Setup Script"));
  console.log(W("═══════════════════════════════════════════════\n"));

  const conn = new Connection(DEVNET_RPC, "confirmed");

  // ── Step 1: Keypair ──────────────────────────────────────────────────────
  let keypair;
  if (fs.existsSync(KEYPAIR_PATH)) {
    console.log(Y("⚠  keypair.json already exists — loading it"));
    const raw = JSON.parse(fs.readFileSync(KEYPAIR_PATH, "utf-8"));
    keypair = Keypair.fromSecretKey(Uint8Array.from(raw));
    console.log(G(`✓  Loaded wallet: ${keypair.publicKey.toBase58()}\n`));
  } else {
    keypair = Keypair.generate();
    fs.writeFileSync(KEYPAIR_PATH, JSON.stringify(Array.from(keypair.secretKey)));
    console.log(G(`✓  Generated new wallet: ${keypair.publicKey.toBase58()}`));
    console.log(Y(`   Saved to: ${KEYPAIR_PATH}`));
    console.log(R(`   ⚠  NEVER commit keypair.json to git!\n`));
  }

  const address = keypair.publicKey.toBase58();

  // ── Step 2: SOL balance check + airdrop ──────────────────────────────────
  console.log(B("Step 1/4: Checking SOL balance..."));
  let lamports = await conn.getBalance(keypair.publicKey);
  let sol = lamports / LAMPORTS_PER_SOL;
  console.log(`   Current balance: ${sol.toFixed(4)} SOL`);

  if (sol < 0.5) {
    console.log(B("   Requesting 2 SOL airdrop (devnet)..."));
    try {
      const sig = await conn.requestAirdrop(keypair.publicKey, 2 * LAMPORTS_PER_SOL);
      await conn.confirmTransaction(sig, "confirmed");
      lamports = await conn.getBalance(keypair.publicKey);
      sol = lamports / LAMPORTS_PER_SOL;
      console.log(G(`✓  Airdrop confirmed. Balance: ${sol.toFixed(4)} SOL\n`));
    } catch (e) {
      console.log(Y(`⚠  Airdrop failed (rate limited). Try manually:`));
      console.log(Y(`   solana airdrop 2 ${address} --url devnet\n`));
    }
  } else {
    console.log(G(`✓  SOL balance OK\n`));
  }

  // ── Step 3: USDC token account ────────────────────────────────────────────
  console.log(B("Step 2/4: Setting up USDC token account..."));
  const usdcAta = await getAssociatedTokenAddress(
    DEVNET_USDC_MINT,
    keypair.publicKey
  );

  const ataInfo = await conn.getAccountInfo(usdcAta);
  if (!ataInfo) {
    console.log("   Creating USDC associated token account...");
    const tx = new Transaction().add(
      createAssociatedTokenAccountInstruction(
        keypair.publicKey,
        usdcAta,
        keypair.publicKey,
        DEVNET_USDC_MINT
      )
    );
    const { blockhash } = await conn.getLatestBlockhash();
    tx.recentBlockhash = blockhash;
    tx.feePayer = keypair.publicKey;
    tx.sign(keypair);
    const sig = await conn.sendRawTransaction(tx.serialize());
    await conn.confirmTransaction(sig, "confirmed");
    console.log(G(`✓  USDC token account created: ${usdcAta.toBase58()}\n`));
  } else {
    console.log(G(`✓  USDC token account exists: ${usdcAta.toBase58()}\n`));
  }

  // ── Step 4: Write .env ────────────────────────────────────────────────────
  console.log(B("Step 3/4: Writing .env file..."));

  const envContent = `# ─── Generated by setup-devnet.js ───────────────────────────────────────────
# Helius RPC — get your free key at https://helius.dev
# Replace YOUR_HELIUS_API_KEY with your actual key
HELIUS_RPC_URL=https://devnet.helius-rpc.com/?api-key=YOUR_HELIUS_API_KEY
HELIUS_WS_URL=wss://devnet.helius-rpc.com/?api-key=YOUR_HELIUS_API_KEY

# Wallet
WALLET_KEYPAIR_PATH=${KEYPAIR_PATH}

# Drift devnet program
DRIFT_PROGRAM_ID=${DRIFT_DEVNET_PROGRAM}

# Network (devnet | mainnet-beta)
SOLANA_NETWORK=devnet

# Vault program (set this after anchor deploy)
VAULT_PROGRAM_ID=11111111111111111111111111111111

# Strategy thresholds
FUNDING_RATE_THRESHOLD=0.0001
BASIS_SPREAD_THRESHOLD=0.01

# Telegram alerts (optional — leave blank to disable)
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=

# Demo mode — logs everything, no real orders sent (true/false)
DEMO_MODE=true
`;

  fs.writeFileSync(ENV_PATH, envContent);
  console.log(G(`✓  .env written to: ${ENV_PATH}`));
  console.log(Y(`   Action needed: replace YOUR_HELIUS_API_KEY with your real key\n`));

  // ── Step 5: Summary ───────────────────────────────────────────────────────
  console.log(B("Step 4/4: Summary\n"));
  console.log(W("Wallet address:  ") + G(address));
  console.log(W("USDC account:    ") + G(usdcAta.toBase58()));
  console.log(W("Network:         ") + Y("Devnet"));
  console.log(W("SOL balance:     ") + G(`${sol.toFixed(4)} SOL`));

  console.log("\n" + W("═══════════════════════════════════════════════"));
  console.log(W(" Remaining manual steps:"));
  console.log(W("═══════════════════════════════════════════════\n"));

  const steps = [
    ["1", "Get a free Helius API key", "https://helius.dev", "Add it to bot/.env"],
    ["2", "Mint devnet USDC", "https://app.drift.trade/?network=devnet", "Connect wallet → deposit → get test USDC"],
    ["3", "Create Drift subaccount", "https://app.drift.trade/?network=devnet", "You need a Drift account to place perp orders"],
    ["4", "Build Anchor program", "cd programs/delta_vault && anchor build", "Generates IDL + target/ folder"],
    ["5", "Deploy to devnet", "anchor deploy --provider.cluster devnet", "Sets your program ID"],
    ["6", "Run the bot", "cd bot && npm install && npm run dev", "DEMO_MODE=true by default — no real orders"],
  ];

  steps.forEach(([n, label, action, note]) => {
    console.log(`  ${Y(n + ".")} ${W(label)}`);
    console.log(`     ${B(action)}`);
    console.log(`     ${note}\n`);
  });

  console.log(G("Setup complete. Run: cd bot && npm run dev\n"));
}

main().catch((e) => {
  console.error(R(`\nSetup failed: ${e.message}`));
  process.exit(1);
});
